apiVersion: apps/v1
kind: Deployment
metadata:
  name: mastermind-sync-api
  labels:
    app: mastermind-sync-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mastermind-sync-api
  template:
    metadata:
      labels:
        app: mastermind-sync-api
    spec:
      containers:
        - name: mastermind-sync-api
          image: mastermind-sync-api:v2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9000
          env:
            - name: NODE_ENV
              value: production
            - name: PORT
              value: "9000"
            - name: LOG_LEVEL
              value: info
            - name: MASTERMIND_SCOPES
              valueFrom:
                secretKeyRef:
                  name: mastermind-sync-api-secrets
                  key: MASTERMIND_SCOPES

            - name: MASTERMIND_SHOPIFY_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: mastermind-sync-api-secrets
                  key: MASTERMIND_SHOPIFY_DOMAIN
            - name: MASTERMIND_REDIRECT_URI
              valueFrom:
                secretKeyRef:
                  name: mastermind-sync-api-secrets
                  key: MASTERMIND_REDIRECT_URI
            - name: MASTERMIND_GRAPHQL_URL
              valueFrom:
                secretKeyRef:
                  name: mastermind-sync-api-secrets
                  key: MASTERMIND_GRAPHQL_URL
            - name: PRISMART_PROXY_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: mastermind-sync-api-secrets
                  key: PRISMART_PROXY_DOMAIN
            - name: CUSTOMER_STORE_CODE
              valueFrom:
                secretKeyRef:
                  name: mastermind-sync-api-secrets
                  key: CUSTOMER_STORE_CODE
            - name: STORE_CODE
              valueFrom:
                secretKeyRef:
                  name: mastermind-sync-api-secrets
                  key: STORE_CODE
            - name: MASTERMIND_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: mastermind-sync-api-secrets
                  key: MASTERMIND_CLIENT_ID
            - name: MASTERMIND_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: mastermind-sync-api-secrets
                  key: MASTERMIND_CLIENT_SECRET
            - name: PRISMART_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mastermind-sync-api-secrets
                  key: PRISMART_USERNAME
            - name: PRISMART_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mastermind-sync-api-secrets
                  key: PRISMART_PASSWORD
