apiVersion: v1
kind: Secret
metadata:
  name: mastermind-sync-api-secrets
type: Opaque
stringData:
  MASTERMIND_CLIENT_ID: your-client-id
  MASTERMIND_CLIENT_SECRET: your-client-secret
  PRISMART_USERNAME: your-username
  PRISMART_PASSWORD: your-password
  MASTERMIND_SCOPES: read_product_listings,read_products
  MASTERMIND_SHOPIFY_DOMAIN: https://your-shopify-domain.com
  MASTERMIND_REDIRECT_URI: https://your-redirect-uri.com
  MASTERMIND_GRAPHQL_URL: https://your-graphql-url.com
  PRISMART_PROXY_DOMAIN: https://your-proxy-domain.com
  CUSTOMER_STORE_CODE: your-customer-store-code
  STORE_CODE: your-store-code