export enum WEBHOOK_SUBSCRIPTION_TOPICS  {
    PRODUCTS_CREATE = 'PRODUCTS_CREATE',
    PRODUCTS_UPDATE = 'PRODUCTS_UPDATE',
    PRODUCTS_DELETE = 'PRODUCTS_DELETE',
    PRODUCTS_PUBLISH = 'PRODUCTS_PUBLISH',
    PRODUCTS_UNPUBLISH = 'PRODUCTS_UNPUBLISH',
    PRODUCTS_ARCHIVE = 'PRODUCTS_ARCHIVE',
    PRODUCTS_UNARCHIVE = 'PRODUCTS_UNARCHIVE',
};

